import os
# x=open("sample.txt","r")
#print(x.read())
#print(x.read(3))
# print(x.readline())
# print(x.readline())
# x.close()
# y=open("sample.txt","a")
# y.write("sometimes by bus")
# y.close()
# z=open("sample.txt","r")
# print(z.read())
# z.close()
# b=open("sample.txt","w")
# b.write("because of rain")
# b.close()
# d=open("sample.txt","r")
# print(d.read())
# d.close()
x1=open("bimple,txt","x")

